# Site settings
title: Coder And The City
header-img: img/home-bg.png
email: feingold.ariel@gmail.com
copyright_name: ArielFeingold
description: > # this means to ignore newlines until "baseurl:"
  My journey into coding 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ArielFeingold
learn_profile: ArielFeingold
email_username: feingold.ariel@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
